package Vista.Forms;

import Modelo.Entidad.Signatario;
import Modelo.Repositorio.Conector;
import Modelo.Repositorio.RepositorioSignatarios;
import Vista.Singletons.BuscadorMuestrasSingleton;
import Vista.Singletons.BuscadorSitiosSingleton;
import Vista.Singletons.PruebasPorSignatarioSingleton;

public class Menu extends javax.swing.JFrame {
    public Signatario sesion;
    private RepositorioSignatarios repoSig = new RepositorioSignatarios();

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        capturarResultados = new javax.swing.JButton();
        capturarResultados1 = new javax.swing.JButton();
        capturarResultados2 = new javax.swing.JButton();
        selMuestra = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        BienvenidaLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 237, 211));

        capturarResultados.setText("Buscador Sitios");
        capturarResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capturarResultadosActionPerformed(evt);
            }
        });

        capturarResultados1.setText("Ver Muestras");
        capturarResultados1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capturarResultados1ActionPerformed(evt);
            }
        });

        capturarResultados2.setText("Capturar resultados");
        capturarResultados2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capturarResultados2ActionPerformed(evt);
            }
        });

        selMuestra.setText("Seleccionar muestra");
        selMuestra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selMuestraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(capturarResultados)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(capturarResultados1))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(capturarResultados2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(selMuestra)))
                                .addContainerGap(60, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(capturarResultados)
                                        .addComponent(capturarResultados1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(capturarResultados2)
                                        .addComponent(selMuestra))
                                .addContainerGap(71, Short.MAX_VALUE)));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        BienvenidaLbl.setText("¡Bienvenido [usuario]!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(BienvenidaLbl)
                                .addGap(0, 0, Short.MAX_VALUE)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(BienvenidaLbl)
                                .addGap(0, 6, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selMuestraActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_selMuestraActionPerformed
        BuscadorMuestras menu = BuscadorMuestrasSingleton.getInstancia();
        menu.setModo(BuscadorMuestras.MODO_BUSQUEDA);
        menu.setVisible(true);
    }// GEN-LAST:event_selMuestraActionPerformed

    private void capturarResultadosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_capturarResultadosActionPerformed
        this.hide();
        BuscadorSitiosSingleton.getInstancia().preparar();
        BuscadorSitiosSingleton.getInstancia().setVisible(true);
    }// GEN-LAST:event_capturarResultadosActionPerformed

    private void capturarResultados1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_capturarResultados1ActionPerformed
        BuscadorMuestras menu = BuscadorMuestrasSingleton.getInstancia();
        menu.preparar();
        menu.setModo(BuscadorMuestras.MODO_VISTA);
        menu.setVisible(true);
    }// GEN-LAST:event_capturarResultados1ActionPerformed

    private void capturarResultados2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_capturarResultados2ActionPerformed
        PruebasPorSignatarioSingleton.getInstancia().preparar(sesion);
        PruebasPorSignatarioSingleton.getInstancia().show();
    }// GEN-LAST:event_capturarResultados2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BienvenidaLbl;
    private javax.swing.JButton capturarResultados;
    private javax.swing.JButton capturarResultados1;
    private javax.swing.JButton capturarResultados2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton selMuestra;

    // End of variables declaration//GEN-END:variables
    public void preparar(){
        try{
            this.sesion = repoSig.searchBy(Conector.getUsr());
            this.BienvenidaLbl.setText("Bienvenido " + sesion.primNombre + " " + sesion.segNombre);
        }
        catch (Exception e){
            e.printStackTrace();
            this.BienvenidaLbl.setText("Bienvenid@");
        }
    }
}
